/**
 * reports.js - Phase 8: Reports & Data Export
 */

const Reports = (() => {

  const DATA = {
    price: `
════════════════════════════════════════
   FARMPRICE DAILY PRICE REPORT
   Date: 20 March 2026 | Tamil Nadu
════════════════════════════════════════
Crop         Mandi        Min   Max   Modal
─────────────────────────────────────────
Tomato       Coimbatore   ₹12   ₹22   ₹18
Onion        Salem        ₹8    ₹15   ₹11
Rice         Madurai      ₹28   ₹45   ₹34
Turmeric     Erode        ₹75   ₹95   ₹85
Banana       Trichy       ₹18   ₹25   ₹21
Cotton       Dindigul     ₹65   ₹82   ₹74
════════════════════════════════════════
Generated by FarmPrice Intelligence System`,

    transactions: `
════════════════════════════════════════
   MY TRANSACTION HISTORY
   Farmer: Murugan | Palladam, Coimbatore
   Period: March 2026
════════════════════════════════════════
TXN-ID       Crop        Qty    Price   Total    Status
──────────────────────────────────────────────────────
TXN-8841     Tomato      200kg  ₹18/kg  ₹3,600   ✅ Done
TXN-9102     Onion       50kg   ₹12/kg  ₹600     ⏳ Pending
TXN-9388     Turmeric    100kg  ₹85/kg  ₹8,500   ● Active
──────────────────────────────────────────────────────
TOTAL EARNED:  ₹12,700
════════════════════════════════════════`,

    savings: `
════════════════════════════════════════
   SAVINGS REPORT — March 2026
   Farmer: Murugan
════════════════════════════════════════
                  Direct Trade  Middleman Est.
Tomato 200kg      ₹3,600        ₹1,600
Onion 50kg        ₹600          ₹300
Turmeric 100kg    ₹8,500        ₹4,000
─────────────────────────────────────────
TOTAL EARNED:     ₹12,700
MIDDLEMAN TOTAL:  ₹5,900
YOU SAVED:        ₹6,800  (53% more!)
════════════════════════════════════════
🌟 தரகர் இல்லாமல் ₹6,800 அதிகம் கிடைத்தது!
   You earned ₹6,800 MORE this month!
`
  };

  function bindTabs() {
    const cards = document.querySelectorAll('.rep-card');
    const viewer = document.getElementById('reportViewer');
    const exportView = document.getElementById('exportView');
    const content = document.getElementById('txReportContainer');

    cards.forEach(card => {
      card.addEventListener('click', () => {
        cards.forEach(c => c.classList.remove('active'));
        card.classList.add('active');

        const repType = card.getAttribute('data-report');
        if (repType === 'export') {
          viewer.style.display = 'none';
          exportView.style.display = 'block';
        } else {
          viewer.style.display = 'block';
          exportView.style.display = 'none';
          
          if(DATA[repType]) {
            content.textContent = DATA[repType].trim();
          }
        }
      });
    });
  }

  function bindActions() {
    document.getElementById('btnPrintRep')?.addEventListener('click', () => window.print());
    
    document.getElementById('btnDltxt')?.addEventListener('click', () => {
      alert("Report saved as report_2026.txt in your downloads folder.");
    });
    
    document.getElementById('btnDlcsv')?.addEventListener('click', () => {
      alert("Report exported as data.csv.");
    });
  }

  // ============================
  // INIT
  // ============================
  async function init() {
    const savedLang = Lang.getSaved();
    if(window.Lang && typeof Lang.load === 'function'){
      await Lang.load(savedLang);
    }
    
    bindTabs();
    bindActions();
    
    if(window.Lang && typeof Lang.applyTranslations === 'function'){
      Lang.applyTranslations();
    }
  }

  return { init };
})();

document.addEventListener('DOMContentLoaded', Reports.init);
